// Copyright 2026 the Underwood Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Scene metrics, provenance, stage work, and prepared output wrappers.
//!
//! This module owns preparation results and their exact accounting; it
//! explicitly does not own scene interaction or visual records.

use super::*;

/// Exact block metrics derived from actual formed line advances and extents.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct TextMetrics {
    size: Size,
    first_baseline: Option<f64>,
    last_baseline: Option<f64>,
}

impl TextMetrics {
    pub(super) fn from_lines<Source>(lines: &[SceneLine<Source>], height: f64) -> Self {
        let width = lines.iter().map(SceneLine::advance).fold(0.0_f64, f64::max);
        Self {
            size: Size::new(width, height),
            first_baseline: lines.first().map(SceneLine::baseline),
            last_baseline: lines.last().map(SceneLine::baseline),
        }
    }

    /// Returns maximum actual line advance and total block-axis extent.
    #[must_use]
    pub const fn size(self) -> Size {
        self.size
    }

    /// Returns the first prepared text baseline, if the scene has a text line.
    #[must_use]
    pub const fn first_baseline(self) -> Option<f64> {
        self.first_baseline
    }

    /// Returns the last prepared text baseline, if the scene has a text line.
    #[must_use]
    pub const fn last_baseline(self) -> Option<f64> {
        self.last_baseline
    }
}

/// One provenance-preserving segment of transient projected scene text.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ProjectedTextSource {
    /// Bytes retained from the immutable committed snapshot.
    Snapshot(SnapshotTextRange),
    /// Bytes generated by the named composition epoch.
    Composition(crate::CompositionTextRange),
}

/// Source-complete range covered by one transient scene observation.
///
/// An interaction unit or glyph can cover more than one segment when a generated
/// combining mark joins an authored base character. Keeping the ordered list
/// prevents either provenance from being fabricated or discarded.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProjectedTextRange {
    sources: Arc<[ProjectedTextSource]>,
}

impl ProjectedTextRange {
    pub(crate) fn new(sources: Vec<ProjectedTextSource>) -> Self {
        Self {
            sources: sources.into(),
        }
    }

    /// Returns ordered, source-complete provenance segments.
    #[must_use]
    pub fn sources(&self) -> &[ProjectedTextSource] {
        &self.sources
    }
}

/// Exact caret position in either committed or generated projected text.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ProjectedTextPosition {
    /// Position in the immutable document snapshot.
    Snapshot(SnapshotTextPosition),
    /// Position in the current generated composition epoch.
    Composition(crate::CompositionTextPosition),
}

/// Immutable prepared scene and exact work report.
#[derive(Clone, Debug)]
pub struct SceneOutput {
    pub(super) scene: TextScene,
    pub(super) work: WorkReport,
}

/// Immutable transient scene for one exact composition epoch.
#[derive(Clone, Debug)]
pub struct CompositionSceneOutput {
    pub(super) scene: CompositionScene,
    pub(super) work: WorkReport,
}

impl CompositionSceneOutput {
    /// Returns the prepared transient scene.
    #[must_use]
    pub const fn scene(&self) -> &CompositionScene {
        &self.scene
    }

    /// Returns actual work performed for this transient request.
    #[must_use]
    pub const fn work(&self) -> &WorkReport {
        &self.work
    }
}

impl SceneOutput {
    /// Returns the prepared scene.
    #[must_use]
    pub const fn scene(&self) -> &TextScene {
        &self.scene
    }

    /// Returns actual work performed for this request.
    #[must_use]
    pub const fn work(&self) -> &WorkReport {
        &self.work
    }
}

/// Count of paragraphs and records processed by one stage.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct StageWork {
    pub(super) paragraphs: usize,
    pub(super) records: usize,
}

impl StageWork {
    pub(super) fn add_paragraph(&mut self, records: usize) {
        self.paragraphs += 1;
        self.records += records;
    }

    /// Returns paragraphs processed rather than reused.
    #[must_use]
    pub const fn paragraphs(self) -> usize {
        self.paragraphs
    }

    /// Returns stage-specific records processed.
    #[must_use]
    pub const fn records(self) -> usize {
        self.records
    }
}

/// Exact stage work performed for one scene request.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct WorkReport {
    pub(super) analysis: StageWork,
    pub(super) itemization: StageWork,
    pub(super) font_selection: StageWork,
    pub(super) shape: StageWork,
    pub(super) line_font_resolution: StageWork,
    pub(super) line_shape: StageWork,
    pub(super) flow: StageWork,
    pub(super) geometry: StageWork,
    pub(super) paint: StageWork,
    pub(super) line_reshapes: usize,
    pub(super) reused_paragraphs: usize,
}

impl WorkReport {
    /// Returns Unicode analysis work.
    #[must_use]
    pub const fn analysis(&self) -> StageWork {
        self.analysis
    }

    /// Returns shaping itemization work.
    #[must_use]
    pub const fn itemization(&self) -> StageWork {
        self.itemization
    }

    /// Returns canonical paragraph font-selection work.
    #[must_use]
    pub const fn font_selection(&self) -> StageWork {
        self.font_selection
    }

    /// Returns canonical paragraph shaping work.
    #[must_use]
    pub const fn shape(&self) -> StageWork {
        self.shape
    }

    /// Returns retained-font resolution performed for line-final shaping.
    #[must_use]
    pub const fn line_font_resolution(&self) -> StageWork {
        self.line_font_resolution
    }

    /// Returns shaping of committed and rejected line candidates.
    #[must_use]
    pub const fn line_shape(&self) -> StageWork {
        self.line_shape
    }

    /// Returns finite-width flow work.
    #[must_use]
    pub const fn flow(&self) -> StageWork {
        self.flow
    }

    /// Returns scene-geometry work.
    #[must_use]
    pub const fn geometry(&self) -> StageWork {
        self.geometry
    }

    /// Returns paint lowering work.
    #[must_use]
    pub const fn paint(&self) -> StageWork {
        self.paint
    }

    /// Returns line-final shaping attempts, including rejected candidates.
    #[must_use]
    pub const fn line_reshapes(&self) -> usize {
        self.line_reshapes
    }

    /// Returns paragraphs reused without calling the adapter.
    #[must_use]
    pub const fn reused_paragraphs(&self) -> usize {
        self.reused_paragraphs
    }
}
