// Copyright 2026 the Underwood Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Scene metrics, provenance, stage work, and prepared output wrappers.
//!
//! This module owns preparation results and their exact accounting; it
//! explicitly does not own scene interaction or visual records.

use super::*;

/// Exact block metrics derived from actual formed line advances and extents.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct TextMetrics {
    size: Size,
    first_baseline: Option<f64>,
    last_baseline: Option<f64>,
}

impl TextMetrics {
    pub(super) fn from_summary(summary: SceneSummary) -> Self {
        Self {
            size: Size::new(summary.max_x - summary.min_x, summary.max_y - summary.min_y),
            first_baseline: summary.first_baseline,
            last_baseline: summary.last_baseline,
        }
    }

    /// Returns the request-space extent, including region offsets and gaps.
    #[must_use]
    pub const fn size(self) -> Size {
        self.size
    }

    /// Returns the first prepared text baseline, if the scene has a text line.
    #[must_use]
    pub const fn first_baseline(self) -> Option<f64> {
        self.first_baseline
    }

    /// Returns the last prepared text baseline, if the scene has a text line.
    #[must_use]
    pub const fn last_baseline(self) -> Option<f64> {
        self.last_baseline
    }
}

/// One provenance-preserving segment of transient projected scene text.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ProjectedTextSource {
    /// Bytes retained from the immutable committed snapshot.
    Snapshot(SnapshotTextRange),
    /// Bytes generated by the named composition epoch.
    Composition(crate::CompositionTextRange),
}

/// Source-complete range covered by one transient scene observation.
///
/// An interaction unit or glyph can cover more than one segment when a generated
/// combining mark joins an authored base character. Keeping the ordered list
/// prevents either provenance from being fabricated or discarded.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProjectedTextRange {
    sources: Arc<[ProjectedTextSource]>,
}

impl ProjectedTextRange {
    pub(crate) fn new(sources: Vec<ProjectedTextSource>) -> Self {
        Self {
            sources: sources.into(),
        }
    }

    /// Returns ordered, source-complete provenance segments.
    #[must_use]
    pub fn sources(&self) -> &[ProjectedTextSource] {
        &self.sources
    }
}

/// Exact caret position in either committed or generated projected text.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ProjectedTextPosition {
    /// Position in the immutable document snapshot.
    Snapshot(SnapshotTextPosition),
    /// Position in the current generated composition epoch.
    Composition(crate::CompositionTextPosition),
}

/// Immutable prepared scene and exact work report.
#[derive(Clone, Debug)]
pub struct SceneOutput {
    pub(super) scene: TextScene,
    pub(super) work: WorkReport,
    pub(super) trace: Option<PreparationTrace>,
    pub(super) region_transcript: Option<RegionTranscript>,
}

/// Immutable transient scene for one exact composition epoch.
#[derive(Clone, Debug)]
pub struct CompositionSceneOutput {
    pub(super) scene: CompositionScene,
    pub(super) work: WorkReport,
    pub(super) trace: Option<PreparationTrace>,
    pub(super) region_transcript: Option<RegionTranscript>,
}

impl CompositionSceneOutput {
    /// Returns the prepared transient scene.
    #[must_use]
    pub const fn scene(&self) -> &CompositionScene {
        &self.scene
    }

    /// Returns actual work performed for this transient request.
    #[must_use]
    pub const fn work(&self) -> &WorkReport {
        &self.work
    }

    /// Returns requested preparation decisions, work, and memory accounting.
    #[must_use]
    pub const fn trace(&self) -> Option<&PreparationTrace> {
        self.trace.as_ref()
    }

    /// Returns replayable region attempts for this transient request.
    #[must_use]
    pub const fn region_transcript(&self) -> Option<&RegionTranscript> {
        self.region_transcript.as_ref()
    }
}

impl SceneOutput {
    /// Returns the prepared scene.
    #[must_use]
    pub const fn scene(&self) -> &TextScene {
        &self.scene
    }

    /// Returns actual work performed for this request.
    #[must_use]
    pub const fn work(&self) -> &WorkReport {
        &self.work
    }

    /// Returns requested preparation decisions, work, and memory accounting.
    #[must_use]
    pub const fn trace(&self) -> Option<&PreparationTrace> {
        self.trace.as_ref()
    }

    /// Returns replayable region attempts for this request.
    #[must_use]
    pub const fn region_transcript(&self) -> Option<&RegionTranscript> {
        self.region_transcript.as_ref()
    }
}

/// Aggregate retained-cache decisions made during one scene preparation.
///
/// Invalidation counters may overlap: one cached paragraph can change both
/// adjustment and paint inputs. Exact reuse, shared preparation, and adapter
/// calls are mutually exclusive outcomes for a paragraph.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct PreparationReuse {
    pub(super) paragraphs: usize,
    pub(super) cold_paragraphs: usize,
    pub(super) preflight_reuses: usize,
    pub(super) exact_geometry_reuses: usize,
    pub(super) shared_preparation_reuses: usize,
    pub(super) adapter_calls: usize,
    pub(super) formation_invalidations: usize,
    pub(super) adjustment_invalidations: usize,
    pub(super) paint_invalidations: usize,
}

impl PreparationReuse {
    /// Returns paragraphs considered by retained preparation.
    #[must_use]
    pub const fn paragraphs(self) -> usize {
        self.paragraphs
    }

    /// Returns paragraphs with no identity-local geometry entry.
    #[must_use]
    pub const fn cold_paragraphs(self) -> usize {
        self.cold_paragraphs
    }

    /// Returns paragraphs accepted from provenance before projection was built.
    #[must_use]
    pub const fn preflight_reuses(self) -> usize {
        self.preflight_reuses
    }

    /// Returns paragraphs that reused exact identity-local geometry.
    #[must_use]
    pub const fn exact_geometry_reuses(self) -> usize {
        self.exact_geometry_reuses
    }

    /// Returns paragraphs prepared from identity-free shared facts.
    #[must_use]
    pub const fn shared_preparation_reuses(self) -> usize {
        self.shared_preparation_reuses
    }

    /// Returns paragraphs sent through the configured formation adapter.
    #[must_use]
    pub const fn adapter_calls(self) -> usize {
        self.adapter_calls
    }

    /// Returns cached paragraphs whose text, shaping, flow, or region key changed.
    #[must_use]
    pub const fn formation_invalidations(self) -> usize {
        self.formation_invalidations
    }

    /// Returns cached paragraphs whose accepted-line adjustment changed.
    #[must_use]
    pub const fn adjustment_invalidations(self) -> usize {
        self.adjustment_invalidations
    }

    /// Returns cached paragraphs whose paint assignment changed.
    #[must_use]
    pub const fn paint_invalidations(self) -> usize {
        self.paint_invalidations
    }
}

/// Deterministic capacity and residency observations for one preparation.
///
/// These values are accounting charges derived from owned collection
/// capacities. They are not allocator telemetry, resident-set size, or
/// wall-clock measurements.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct PreparationMemory {
    pub(super) cache_before: CacheDiagnostics,
    pub(super) cache_after: CacheDiagnostics,
    pub(super) scene_output_capacity_bytes: usize,
    pub(super) scratch_capacity_before: usize,
    pub(super) scratch_capacity_after: usize,
}

impl PreparationMemory {
    /// Returns retained-cache state before preparation.
    #[must_use]
    pub const fn cache_before(self) -> CacheDiagnostics {
        self.cache_before
    }

    /// Returns retained-cache state after preparation and budget enforcement.
    #[must_use]
    pub const fn cache_after(self) -> CacheDiagnostics {
        self.cache_after
    }

    /// Returns the payload-byte charge for scene-spine nodes newly retained by
    /// this publication relative to its reusable prior spine.
    ///
    /// Shared spine nodes contribute zero. Paragraph geometry and its owned
    /// collection capacities are reported through the scene-cache diagnostics
    /// instead.
    #[must_use]
    pub const fn scene_output_capacity_bytes(self) -> usize {
        self.scene_output_capacity_bytes
    }

    /// Returns reusable layout scratch capacity before preparation.
    #[must_use]
    pub const fn scratch_capacity_before(self) -> usize {
        self.scratch_capacity_before
    }

    /// Returns reusable layout scratch capacity after preparation.
    #[must_use]
    pub const fn scratch_capacity_after(self) -> usize {
        self.scratch_capacity_after
    }

    /// Returns reusable layout scratch growth during preparation.
    #[must_use]
    pub const fn scratch_growth_bytes(self) -> usize {
        self.scratch_capacity_after
            .saturating_sub(self.scratch_capacity_before)
    }
}

/// Opt-in deterministic explanation of one successful scene preparation.
///
/// Exact region slots remain available through
/// [`SceneOutput::region_transcript`] or
/// [`CompositionSceneOutput::region_transcript`]. Host timing and process
/// allocation counts intentionally remain outside this `no_std` core.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PreparationTrace {
    pub(super) work: WorkReport,
    pub(super) reuse: PreparationReuse,
    pub(super) memory: PreparationMemory,
    pub(super) region_attempts: usize,
    pub(super) region_height_rejections: usize,
}

impl PreparationTrace {
    /// Returns actual stage work performed by the request.
    #[must_use]
    pub const fn work(&self) -> &WorkReport {
        &self.work
    }

    /// Returns retained reuse and invalidation decisions.
    #[must_use]
    pub const fn reuse(&self) -> PreparationReuse {
        self.reuse
    }

    /// Returns deterministic capacity and cache-residency observations.
    #[must_use]
    pub const fn memory(&self) -> PreparationMemory {
        self.memory
    }

    /// Returns exact-region slot attempts made during preparation.
    #[must_use]
    pub const fn region_attempts(&self) -> usize {
        self.region_attempts
    }

    /// Returns region attempts rejected because the offered slot was too short.
    #[must_use]
    pub const fn region_height_rejections(&self) -> usize {
        self.region_height_rejections
    }
}

/// Count of paragraphs and records processed by one stage.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct StageWork {
    pub(super) paragraphs: usize,
    pub(super) records: usize,
}

impl StageWork {
    pub(super) fn add_paragraph(&mut self, records: usize) {
        self.paragraphs += 1;
        self.records += records;
    }

    /// Returns paragraphs processed rather than reused.
    #[must_use]
    pub const fn paragraphs(self) -> usize {
        self.paragraphs
    }

    /// Returns stage-specific records processed.
    #[must_use]
    pub const fn records(self) -> usize {
        self.records
    }
}

/// Exact stage work performed for one scene request.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct WorkReport {
    pub(super) analysis: StageWork,
    pub(super) itemization: StageWork,
    pub(super) font_selection: StageWork,
    pub(super) shape: StageWork,
    pub(super) line_font_resolution: StageWork,
    pub(super) line_shape: StageWork,
    pub(super) flow: StageWork,
    pub(super) adjustment: StageWork,
    pub(super) geometry: StageWork,
    pub(super) paint: StageWork,
    pub(super) line_reshapes: usize,
    pub(super) line_candidates: u32,
    pub(super) rejected_line_candidates: u32,
    pub(super) line_checkpoint_restores: u32,
    pub(super) reused_paragraphs: usize,
    pub(super) shared_preparations: usize,
}

impl WorkReport {
    /// Returns Unicode analysis work.
    #[must_use]
    pub const fn analysis(&self) -> StageWork {
        self.analysis
    }

    /// Returns shaping itemization work.
    #[must_use]
    pub const fn itemization(&self) -> StageWork {
        self.itemization
    }

    /// Returns canonical paragraph font-selection work.
    #[must_use]
    pub const fn font_selection(&self) -> StageWork {
        self.font_selection
    }

    /// Returns canonical paragraph shaping work.
    #[must_use]
    pub const fn shape(&self) -> StageWork {
        self.shape
    }

    /// Returns retained-font resolution performed for line-final shaping.
    #[must_use]
    pub const fn line_font_resolution(&self) -> StageWork {
        self.line_font_resolution
    }

    /// Returns shaping of committed and rejected line candidates.
    #[must_use]
    pub const fn line_shape(&self) -> StageWork {
        self.line_shape
    }

    /// Returns finite-width flow work.
    #[must_use]
    pub const fn flow(&self) -> StageWork {
        self.flow
    }

    /// Returns accepted-slot alignment and justification work.
    #[must_use]
    pub const fn adjustment(&self) -> StageWork {
        self.adjustment
    }

    /// Returns scene-geometry work.
    #[must_use]
    pub const fn geometry(&self) -> StageWork {
        self.geometry
    }

    /// Returns paint lowering work.
    #[must_use]
    pub const fn paint(&self) -> StageWork {
        self.paint
    }

    /// Returns line-final shaping attempts, including rejected candidates.
    #[must_use]
    pub const fn line_reshapes(&self) -> usize {
        self.line_reshapes
    }

    /// Returns proposed line candidates, including retry candidates.
    #[must_use]
    pub const fn line_candidates(&self) -> usize {
        self.line_candidates as usize
    }

    /// Returns line candidates rejected by line-final fit checks.
    #[must_use]
    pub const fn rejected_line_candidates(&self) -> usize {
        self.rejected_line_candidates as usize
    }

    /// Returns line candidates committed to the current scene.
    #[must_use]
    pub const fn accepted_line_candidates(&self) -> usize {
        self.line_candidates
            .saturating_sub(self.rejected_line_candidates) as usize
    }

    /// Returns restorations of line traversal and provisional output.
    #[must_use]
    pub const fn line_checkpoint_restores(&self) -> usize {
        self.line_checkpoint_restores as usize
    }

    /// Returns paragraphs reused without calling the adapter.
    #[must_use]
    pub const fn reused_paragraphs(&self) -> usize {
        self.reused_paragraphs
    }

    /// Returns paragraphs whose identity-free prepared facts were shared from
    /// another consumer.
    #[must_use]
    pub const fn shared_preparations(&self) -> usize {
        self.shared_preparations
    }
}
